### ISSUE TITLE
Add translation file for Spanish (Spain).

### ISSUE THREAD

**Issue by Arkathus** [Hir0shiyt/RandomEnchantments2#4]
I have created a translation of the mod into Spanish (Spain), which is my native language, to play more comfortably alongside the 'Enchantment Descriptions' mod, and I would like to share it with the community that uses this beautiful mod. By the way, thank you very much for bringing it to these versions. I greatly enjoyed the original mod in version 1.12.2, and now I can finally enjoy it in these latest versions. I appreciate you making it happen. If you want, for future projects you want to do, you can count on me as a translator into Spanish (for now, only Spanish; I'm still trying to achieve other languages).
[es_es.json](https://github.com/Hir0shiyt/RandomEnchantments2/files/14383255/es_es.json)

**Comment by Baldthret** [comment]
I tried to add it as a pull request, but it was denied because I am not a collaborator.

**Comment by Hir0shiyt** [comment]
I will be integrating this file as soon as I can, I really appreciate what you did there, and I believe it's going to help a lot of people. The credits will be given at the very bottom of the mod page when the files are released

**Comment by Arkathus** [comment]
I have corrected the file. It wasn't working properly due to some lines not being closed. As always, it's better to carefully review what you do, even after many sleepless hours. This is the corrected and functioning file.

[es_es.json](https://github.com/Hir0shiyt/RandomEnchantments2/files/14387793/es_es.json)

**Comment by Hir0shiyt** [comment]
I had already noticed that and I thought I'd have to do that, but you also realized so thank you for saving me some time.

**Comment by Arkathus** [comment]
A pleasure to be able to help.

**Comment by Hir0shiyt** [comment]
Close and merged as pull request
